### ISSUE TITLE
About lossless compression

### ISSUE THREAD

**Issue by jump44722** [BYchao100/Deep-Lossy-Plus-Residual-Coding#2]
Thank you for providing the model.
When I performed lossless compression using the model you uploaded, the following image was output.
Do you know of any solutions to this problem?
![kodim01_rec](https://github.com/BYchao100/Deep-Lossy-Plus-Residual-Coding/assets/160721547/53ed5088-5c57-4b42-88cf-91f8a23de90d)

**Comment by BYchao100** [comment]
> Thank you for providing the model. When I performed lossless compression using the model you uploaded, the following image was output. Do you know of any solutions to this problem?

It is probably due to the different runtime environments of the code, such as different pytorch version, cuda version. You can try the environment I recommend or try cpu ('device = torch.device('cpu')' ) instead of gpu.

**Comment by bblgbr** [comment]
I also got the same result even trying cpu ('device = torch.device('cpu')' ) instead of gpu. Do you know of any solutions to this problem? Thanks.

**Comment by BYchao100** [comment]
> I also got the same result even trying cpu ('device = torch.device('cpu')' ) instead of gpu. Do you know of any solutions to this problem? Thanks.

What is your running environment? Can you try the same running environment as I did to see if it is ok?

**Comment by bblgbr** [comment]
> > I also got the same result even trying cpu ('device = torch.device('cpu')' ) instead of gpu. Do you know of any solutions to this problem? Thanks.
> 
> What is your running environment? Can you try the same running environment as I did to see if it is ok?

Sorry, I use the torch 2.2.1+cu118 and after changing to 1.11.0, I could get the correct result on cpu. Because the cuda version is different, I couldn't run on gpu right now and I will try it in the future. In a word, thanks very much.

**Comment by BYchao100** [comment]
> > > I also got the same result even trying cpu ('device = torch.device('cpu')' ) instead of gpu. Do you know of any solutions to this problem? Thanks.
> > 
> > 
> > What is your running environment? Can you try the same running environment as I did to see if it is ok?
> 
> Sorry, I use the torch 2.2.1+cu118 and after changing to 1.11.0, I could get the correct result on cpu. Because the cuda version is different, I couldn't run on gpu right now and I will try it in the future. In a word, thanks very much.

That's great!

**Comment by jump44722** [comment]
> > Thank you for providing the model. When I performed lossless compression using the model you uploaded, the following image was output. Do you know of any solutions to this problem?
> 
> It is probably due to the different runtime environments of the code, such as different pytorch version, cuda version. You can try the environment I recommend or try cpu ('device = torch.device('cpu')' ) instead of gpu.

When I try to run the program with the right version, I get a torchac compile error and cannot run it correctly.
Do you know of a solution?
Thank you.
```
~/dlpr/venv_dlpr$ python torchac_test.py 
Using /home/test/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Emitting ninja build file /home/test/.cache/torch_extensions/py39_cu113/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.1.git.kitware.jobserver-1
Loading extension module torchac_backend...
Traceback (most recent call last):
  File "/home/test/dlpr/venv_dlpr/torchac_test.py", line 1, in <module>
    import torchac
  File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torchac/__init__.py", line 2, in <module>
    from torchac.torchac import encode_float_cdf
  File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torchac/torchac.py", line 13, in <module>
    torchac_backend = load(
  File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1382, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1775, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/test/.cache/torch_extensions/py39_cu113/torchac_backend/torchac_backend.so: cannot open shared object file: No such file or directory

```

**Comment by BYchao100** [comment]
> > > Thank you for providing the model. When I performed lossless compression using the model you uploaded, the following image was output. Do you know of any solutions to this problem?
> > 
> > 
> > It is probably due to the different runtime environments of the code, such as different pytorch version, cuda version. You can try the environment I recommend or try cpu ('device = torch.device('cpu')' ) instead of gpu.
> 
> When I try to run the program with the right version, I get a torchac compile error and cannot run it correctly. Do you know of a solution? Thank you.
> 
> ```
> ~/dlpr/venv_dlpr$ python torchac_test.py 
> Using /home/test/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
> Emitting ninja build file /home/test/.cache/torch_extensions/py39_cu113/torchac_backend/build.ninja...
> Building extension module torchac_backend...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> 1.11.1.git.kitware.jobserver-1
> Loading extension module torchac_backend...
> Traceback (most recent call last):
>   File "/home/test/dlpr/venv_dlpr/torchac_test.py", line 1, in <module>
>     import torchac
>   File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torchac/__init__.py", line 2, in <module>
>     from torchac.torchac import encode_float_cdf
>   File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torchac/torchac.py", line 13, in <module>
>     torchac_backend = load(
>   File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
>     return _jit_compile(
>   File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1382, in _jit_compile
>     return _import_module_from_library(name, build_directory, is_python_module)
>   File "/home/test/dlpr/venv_dlpr/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1775, in _import_module_from_library
>     module = importlib.util.module_from_spec(spec)
> ImportError: /home/test/.cache/torch_extensions/py39_cu113/torchac_backend/torchac_backend.so: cannot open shared object file: No such file or directory
> ```

You can try pip install torchac==0.9.3 to see if it is ok.
